source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api/', include('myapi.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/myapi/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import LikeViewSet, CommentViewSet

router = routers.DefaultRouter()
router.register(r'likes', LikeViewSet)
router.register(r'comments', CommentViewSet)


app_name = 'myapi'

urlpatterns = [
    path('', include(router.urls)),

]

source/webapp/urls.py
from django.urls import path
from .views import IndexView, PhotoCreateView, PhotoDeleteView, PhotoUpdateView, PhotoView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('photo/create/', PhotoCreateView.as_view(), name='photo_create'),
    path('photo/<int:pk>/', PhotoView.as_view(), name='photo_detail'),
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('login/', LoginView.as_view(), name='login'),

    path('logout/', LogoutView.as_view(), name='logout')
]

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Image(models.Model):
    photo = models.ImageField(upload_to='gallery_images', null=False, blank=False, verbose_name='Photo')
    sign = models.TextField(max_length=200, null=False, blank=False, verbose_name="Subscription")
    likenum = models.IntegerField(null=False, blank=False, default=0, verbose_name="Like quantity")
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='authors')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')
    userlike = models.ManyToManyField(User, through='webapp.Like',  blank=True, verbose_name='userslike')


class Comment(models.Model):
    text = models.TextField(max_length=1000,null=False, blank=False, verbose_name="text")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='author')
    photo = models.ForeignKey('Image', on_delete=models.CASCADE, related_name="comments")

class Like(models.Model):
    photo = models.ForeignKey(Image, on_delete=models.CASCADE, null=True, blank=True, verbose_name='photo', related_name='photolikes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='author', related_name='userlikes')

source/webapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import widgets

from webapp.models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['photo', 'sign']

source/myapi/views.py
from rest_framework import viewsets
from rest_framework.permissions import DjangoModelPermissions, IsAuthenticatedOrReadOnly, IsAuthenticated, AllowAny
from rest_framework.response import Response

SAFE_METHODS = ('GET', 'HEAD', 'OPTIONS')

from .serializers import LikeSerializer, CommentSerializer
from webapp.models import Like, Comment, Image


class LikeViewSet(viewsets.ModelViewSet):
    permission_classes = [DjangoModelPermissions]
    serializer_class = LikeSerializer
    queryset = Like.objects.all()

    def create(self, request, *args, **kwargs):
        pk = request.data.get('photo')
        photo = Image.objects.get(pk=pk)
        # print(pk,photo)
        # print(self.queryset.filter(photo=photo))
        if self.queryset.filter(photo=photo):
            return Response({'error': 'You have already liked it'}, status=400)
        photo.likenum += 1
        photo.save()
        return super(LikeViewSet, self).create(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        pk = request.data.get('photo')
        photo = Image.objects.get(pk=pk)
        if not self.queryset.filter(photo=photo):
            return Response({'error': 'No likes yet'}, status=400)
        photo.likenum -= 1
        photo.save()
        return super(LikeViewSet, self).create(request, *args, **kwargs)


class CommentViewSet(viewsets.ModelViewSet):
    permission_classes = [DjangoModelPermissions]
    serializer_class = CommentSerializer
    queryset = Comment.objects.all()


    def get_permissions(self):
        if self.request.method in SAFE_METHODS:
          return [AllowAny()]

        elif self.request.method == 'POST':
            return [IsAuthenticated()]
        else:
            return [DjangoModelPermissions()]

source/webapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from webapp.forms import ImageForm
from webapp.models import Image


class IndexView(ListView):
    model = Image
    template_name = 'index.html'
    context_object_name = 'photo_list'
    ordering = '-created_at'


class PhotoView(DetailView):
    model = Image
    template_name = 'photo/view.html'
    context_object_name = 'photo'


class PhotoCreateView(LoginRequiredMixin,CreateView):
    model = Image
    template_name = 'photo/create.html'
    form_class = ImageForm

    def get_success_url(self):
        return reverse('webapp:photo_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        self.object = Image.objects.create(author=self.request.user, photo=form.cleaned_data['photo'],
                                           sign=form.cleaned_data['sign'])

        return HttpResponseRedirect(self.get_success_url())


class PhotoUpdateView(PermissionRequiredMixin, UpdateView):
    model = Image
    template_name = 'photo/update.html'
    form_class = ImageForm
#    fields = ('name', 'category', 'photo', 'description')
    context_object_name = 'photo'
    permission_denied_message = 'Access Denied!'
    permission_required = 'webapp.change_image'

    def has_permission(self):
        image = Image.objects.get(pk=self.kwargs['pk'])
        if image.author == self.request.user or super().has_permission():
            return True

    def get_success_url(self):
        return reverse('webapp:photo_detail', kwargs={'pk': self.object.pk})


class PhotoDeleteView(PermissionRequiredMixin, DeleteView):
    model = Image
    template_name = 'photo/delete.html'
    success_url = reverse_lazy('webapp:index')
    context_object_name = 'photo'
    permission_denied_message = 'Access Denied!'
    permission_required = 'webapp.delete_image'

    def has_permission(self):
        image = Image.objects.get(pk=self.kwargs['pk'])
        if image.author == self.request.user or super().has_permission():
            return True

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}MySite{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar">
    <div class="container">
        <ul class="menu">
             <li><a href="{% url 'webapp:index' %}">Home</a></li>
            {% if request.user.is_authenticated %}
                <li> <p> Привет, {{ request.user }} </li>
                <li><a href="{% url 'webapp:logout' %}">Log Out</a></li>
            {% else %}
                <li><a href="{% url 'webapp:login' %}">Log In</a></li>
            {% endif %}
            {% block menu %}{% endblock %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Gallery{% endblock %}
{% block menu %}
{#    {% if perms.webapp.add_product and perms.webapp.can_have_piece_of_pizza %}#}
      {% if request.user.is_authenticated %}
         <li class="nav-item"><a href="{% url "webapp:photo_create" %}" class="nav-link">add photo </a></li>
      {% endif %}
{% endblock %}
{% block content %}
    <h1 class="text-center">Gallery</h1>
    <div class="row">
        {% for photo in photo_list %}
            <div class="col col-3">
                <div class="card">
                     {% if photo.photo %}
                        <img class="avatar" src="{{ photo.photo.url }}">
                     {% else %}
                            <img class="avatar" src="{% static "pics/index.jpeg" %}" alt="My image"/>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ photo.sign }}</h5>
                        <p class="card-text">{{ photo.author}} | {{ photo.created_at }} | {{ photo.likenum }} </p>
                        <a href="{% url "webapp:photo_detail" photo.pk %}" class="btn btn-primary"> view </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
    <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    <p>{{ field }}</p>
    {% for error in field.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
{% endfor %}

<p><input type="submit" value="{{ button_text }}"></p>

source/webapp/templates/photo/create.html
{% extends 'base.html' %}
{% block title %}Add photo{% endblock %}
{% block content %}
    <h1 class="text-center">Create photo</h1>
    <form action="{% url "webapp:photo_create" %}" method="POST" enctype="multipart/form-data">
         {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

source/webapp/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %}Delete Photo{% endblock %}
{% block content %}
    <h3 class="text-center">Delete photo {{ photo }} </h3>
    <form class="text-center" action="{% url "webapp:photo_delete" photo.pk %}"
          method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" value="ОК" class="btn btn-danger">
        <a href="{% url 'webapp:index' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

source/webapp/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}Update photo{% endblock %}
{% block content %}
    <h1 class="text-center">update photo</h1>
    <form action="{% url "webapp:photo_update" photo.pk %}" method="POST" enctype="multipart/form-data">
         {% include 'partial/form.html' with button_text="update" %}
    </form>
{% endblock %}

source/webapp/templates/photo/view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ photo.sign }}{% endblock %}

{% block menu %}
    {% if perms.webapp.change_photo or request.user == photo.author%}
     <li><a href="{% url 'webapp:photo_delete' photo.pk%}"> Delete photo </a>
    {% endif %}
    {% if perms.webapp.change_photo or request.user == photo.author%}
     <li><a href="{% url 'webapp:photo_update' photo.pk %}"> Update photo </a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <p class="text-center">
        <h1>{{ photo.sign }}</h1>
        <div class="row">
            <div class="col col-12 col-sm-10 col-md-8 col-lg-6 m-auto">
               {% if photo.photo %}
                  <img src="{{ photo.photo.url }}" class="img-fluid" alt="{{ photo.sign }}">
                {% else %}
                    <img class="avatar" src="{% static "pics/index.jpeg" %}" alt="My image"/>
                {% endif %}

            </div>
        </div>
        <p>{{ photo.sign }}</p>
        <p>{{ photo.author}}</p>
        <p>{{ photo.created_at }}</p>
        <p>{{ photo.likenum }} </p>

    <hr>
    {% for comment in photo.comments.all %}
        <div class="comment">
            <p> Автор: {{ photo.author }} </p>
            <p> Created at {{ comment.created_at|date:'Y-m-d H:i:s' }}</p>
            <div class="pre">{{ comment.text }}</div>
     {% endfor %}
     <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#CommentModal">Add comment</button>


<div class="modal fade" id="CommentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="CommentModal">Add comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}